# Generated by Django 4.0.4 on 2022-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='mainactor',
            field=models.CharField(max_length=50, verbose_name='Главный актер фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='price',
            field=models.IntegerField(verbose_name='Цена фильма в кинотеатре'),
        ),
    ]
