# Generated by Django 4.0.4 on 2022-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_films_mainactor_alter_films_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='price',
        ),
        migrations.AddField(
            model_name='films',
            name='year',
            field=models.IntegerField(default=2000, verbose_name='Год выпуска фильма'),
        ),
    ]
